const express = require('express')
const app = express()
const topicsController = require('./controllers/topicsController')
app.set('view engine', 'ejs')
app.get('/', topicsController.getTopics)
app.listen(3000, () => {    
    console.log('Servidor corriendo en http://localhost:3000')
})
app.use(express.urlencoded({extended: true}))
app.post('/topics', topicsController.createTopic)
app.post('/topics/:id/delete', topicsController.deleteTopic)
app.post('/topics/:id/update', topicsController.updateTopic)
app.post('/topics/:id/links', topicsController.createLink)
app.post('/topics/:id/links/:linkId/delete', topicsController.deleteLink)
app.post('/topics/:id/links/:linkId/update', topicsController.updateLink)
app.post('/topics/:id/vote', topicsController.voteTopic)
app.post('/topics/:id/links/:linkId/vote', topicsController.voteLink)